yandex/yatagan

codegen/impl/src/main/kotlin/ScopedProviderGenerator.kt, rt/engine/src/main/kotlin/accessStrategies.kt, testing/tests/src/test/kotlin/RuntimeTest.kt
RT behaved inconsistently with generated code,
and there was one more inconsistency with the latter itself.
Cover the fix with a test.
Fixes #12
=> Fix: thread access inconsistency between backends.

codegen/impl/src/main/kotlin/AccessStrategyManager.kt, codegen/impl/src/main/kotlin/ComponentGenerator.kt, codegen/impl/src/main/kotlin/ComponentGeneratorFacade.kt, codegen/impl/src/main/kotlin/SlotSwitchingGenerator.kt, codegen/impl/src/main/kotlin/accessStrategies.kt, processor/common/src/main/kotlin/Options.kt, processor/common/src/main/kotlin/process.kt, rt/engine/src/main/kotlin/RuntimeComponent.kt, testing/tests/src/main/kotlin/CompileTestDriverBase.kt, testing/tests/src/test/kotlin/HeavyTest.kt
Introduce an `yatagan.experimental.maxSlotsPerSwitch`
option to enable/customize nested switches behavior.
It's set to infinity by default as before the patch.
Add a "heavy" test-case to trigger this mechanic.
Resolves #8
=> Codegen: implement nested switches in switching providers.

codegen/impl/src/main/kotlin/AccessStrategyManager.kt, core/graph/impl/src/main/kotlin/BindingGraphImpl.kt
Before this fix the optimization algorithm couldn't look through
alias chains thus missing potential cases to optimize.
Closes #35
=> Fix: Properly resolve aliases while computing caching omission.

core/model/impl/src/main/kotlin/ComponentFactoryWithBuilderModelImpl.kt, core/model/impl/src/main/kotlin/ComponentModelImpl.kt, lang/rt/src/main/kotlin/reflectionUtils.kt, testing/tests/src/test/kotlin/ComponentCreatorFailureTest.kt, testing/tests/src/test/kotlin/ComponentHierarchyKotlinTest.kt, testing/tests/src/test/resources/golden/ComponentCreatorFailureTest/invalid-component-creator.golden.txt, validation/format/src/main/kotlin/Strings.kt
Dagger allows `create(): ComponentBase` in `DerivedComponent`'s `Builder`.
this allows to inherit such `create()` methods from builder's superinterfaces.
Fixes #40
=> Enhance: Allow for @Builder's factory methods to return supertypes

core/model/impl/src/main/kotlin/bindingModelsImpl.kt, testing/tests/src/test/kotlin/CoreBindingsFailureTest.kt, testing/tests/src/test/kotlin/MultibindingsTest.kt, testing/tests/src/test/resources/golden/CoreBindingsFailureTest/invalid-map-binding.golden.txt, validation/format/src/main/kotlin/Strings.kt
=> Enhance: Allow IntoMap.Key annotations to have non-"value" attributes.

api/compiled/src/main/resources/META-INF/proguard/yatagan.pro
Fixes #46
Tests for minified builds (Android) are currently planned in #20
=> Fix: Replace `create` with `autoBuilder` in minifier config.

api/dynamic/src/main/kotlin/Yatagan.kt, core/graph/impl/src/main/kotlin/BindingGraphImpl.kt, core/graph/impl/src/main/kotlin/GraphBindingsManager.kt, core/graph/impl/src/main/kotlin/Options.kt, processor/common/src/main/kotlin/Options.kt, processor/common/src/main/kotlin/process.kt, rt/engine/src/main/kotlin/RuntimeEngine.kt, testing/tests/src/main/kotlin/CompileTestDriver.kt, testing/tests/src/main/kotlin/CompileTestDriverBase.kt, testing/tests/src/main/kotlin/DynamicCompileTestDriver.kt, testing/tests/src/test/kotlin/CoreBindingsFailureTest.kt, testing/tests/src/test/resources/golden/CoreBindingsFailureTest/conflicting-aliases-with-an-option.golden.txt, testing/tests/src/test/resources/golden/CoreBindingsFailureTest/conflicting-bindings.golden.txt, validation/format/src/main/kotlin/reporting.kt
1. Report duplicate `@Binds` as a warning unconditionally.
2. If the option is enabled, report as an error.
Fixes #48
=> Fix: Introduce reportDuplicateAliasesAsErrors option.

core/graph/impl/src/main/kotlin/GraphBindingsManager.kt, testing/tests/src/test/kotlin/CoreBindingsFailureTest.kt, testing/tests/src/test/resources/golden/CoreBindingsFailureTest/conflicting-bindings.golden.txt
The case where there is at most one non-alias binding among the duplicates
is reported as error, whereas should be a warning.
Linked to #48
=> Fix: handle the corner case for duplicate aliases reporting.

core/graph/impl/src/main/kotlin/BindingGraphImpl.kt, testing/tests/src/test/kotlin/CoreBindingsFailureTest.kt, testing/tests/src/test/resources/golden/CoreBindingsFailureTest/alias-in-super-alias-in-sub-bug-54-.golden.txt
If the alias is included into a super component, while another dependent alias
is included into a sub, and the string representation of a list-binding is
queried, which involves resolving the second alias in the sub - crash!
This CL fixes long existing graph building inconsistency -
if an alias is included from the super-component, binding materialization
continues locally after the alias resolution, not in the parent.
Fixes #54
=> Fix: Materialization/resolution inconsistency.

core/graph/impl/src/main/kotlin/GraphBindingsManager.kt, core/graph/impl/src/main/kotlin/bindings/SyntheticAliasBindingImpl.kt, core/graph/impl/src/main/kotlin/bindings/utils.kt, testing/tests/src/test/kotlin/MultibindingsTest.kt
Also remove sourceBinding resolution in favor of directly passing it
to constructor as the latter was possible from the start.
Fixes #58
Note: `SyntheticAliasBindingImpl` is used (among some similar purposes) to bind `List<T>` and `List<? extends T>` nodes to the same binding.
=> Fix: Correctly handle synthetic alias bindings in conflict checks.

api/public/src/main/kotlin/Condition.kt, api/public/src/main/kotlin/ConditionExpression.kt, base/src/main/kotlin/sets.kt, base/src/main/kotlin/util.kt, core/model/api/src/main/kotlin/ConditionalHoldingModel.kt, core/model/impl/build.gradle.kts, core/model/impl/src/main/kotlin/ConditionModelImpl.kt, core/model/impl/src/main/kotlin/ConditionalHoldingModelImpl.kt, core/model/impl/src/main/kotlin/FeatureModelImpl.kt, core/model/impl/src/main/kotlin/parsing/BooleanExpressionParser.kt, core/model/impl/src/main/kotlin/parsing/ExpressionFactoryForParsing.kt, core/model/impl/src/main/kotlin/parsing/ParseException.kt, core/model/impl/src/test/kotlin/BooleanExpressionParserTest.kt, lang/api/src/main/kotlin/BuiltinAnnotation.kt, lang/compiled/src/main/kotlin/CtAnnotationDeclarationBase.kt, lang/compiled/src/main/kotlin/CtTypeDeclarationBase.kt, lang/compiled/src/main/kotlin/builtinAnnotationImpls.kt, lang/jap/src/main/kotlin/JavaxAnnotationImpl.kt, lang/ksp/src/main/kotlin/KspAnnotationImpl.kt, lang/rt/src/main/kotlin/RtTypeDeclarationImpl.kt, lang/rt/src/main/kotlin/builtinAnnotationImpls.kt, testing/tests/src/test/kotlin/ConditionsTest.kt, testing/tests/src/test/kotlin/CoreBindingsFailureTest.kt, testing/tests/src/test/resources/golden/ConditionsTest/invalid-conditions-expression-test.golden.txt, testing/tests/src/test/resources/golden/CoreBindingsFailureTest/invalid-conditions.golden.txt, testing/tests/src/test/resources/golden/CoreBindingsFailureTest/invalid-features-variants.golden.txt, validation/format/src/main/kotlin/Strings.kt
This is in a way Conditions API 2.0, which
we are able to introduce as the "legacy" API is not stable yet.
This realizes the full potential of the support for the arbitrary
boolean expressions, implemented in #67.
Legacy is API is left fully intact and working, the new
API can be used besides the old.
Closes #65.
=> Api: Implement `ConditionExpression` API.

core/graph/impl/src/main/kotlin/GraphBindingsManager.kt, core/graph/impl/src/main/kotlin/bindings/AliasBindingImpl.kt, testing/tests/src/main/kotlin/CompileTestDriverBase.kt, testing/tests/src/test/kotlin/CoreBindingsFailureTest.kt, testing/tests/src/test/resources/golden/CoreBindingsFailureTest/case-for-88.golden.txt
Before this was implemented as equals/hashCode in AliasBindingImpl,
which was affecting the correct work of the validation pipeline.
So this CL moves the alias comparison logic to GraphBindingsManager.
Fixes #88
=> Fix: Move alias duplicate check to GraphBindingsManager.

LICENSES, gradle/libs.versions.toml, testing/procedural/src/main/kotlin/ClassNames.kt, testing/procedural/src/main/kotlin/generate.kt, testing/tests/build.gradle.kts
Mockito drastically slows the tests down, so replace heavy mockito machinery with a naive custom implementation, as it is enough for the tests.
=> Tests: Remove mockito usage from heavy tests.

api/common/src/main/kotlin/loadImplementation.kt
=> Keep enclosing class

gradle/libs.versions.toml, lang/jap/src/main/kotlin/com/yandex/yatagan/lang/jap/JavaxAnnotatedImpl.kt
This update bumps the internal Kotlin version used to compile test cases to 1.9.0, which has KAPT annotation reversing fixed (see #74 for more info) So, as nice version-dependent solution is almost impossible, we just unconditionally use normal annotation order.
=> Testing: Update room-compiler-processing-testing to 2.6.0

api/public/src/main/kotlin/Optional.kt
Current version of #orElse method forces to create alternative version **before** choosing inside #orElse method, which could be useless with non-empty Optional.
This commit adds another version of #orElse method that allows to create alternative only when Optional is empty.
=> Provide Optional#orElse method with lazily alternative creation

.github/workflows/main.yaml, gradle/libs.versions.toml
new version is lighter and does not depend on the ANTLR library which may cause conflicts at runtime.
Closes #145 
`gradle-build-action` is replaced with `gradle/actions/setup-gradle`, as per it migration guide. The former is deprecated.
=> Update logicng to 2.5.0

codegen/impl/src/main/kotlin/com/yandex/yatagan/codegen/impl/SlotSwitchingGenerator.kt, testing/tests/src/main/kotlin/com/yandex/yatagan/testing/tests/CompileTestDriverBase.kt
[Refactor + Fix: Refactor slot switch generator.](https://github.com/yandex/yatagan/commit/1ac5a9f409e19052dc66c40dcde40fe8516fa504) 
Fixes the hardcoded 100 slots (whoops!)
Uses `chunked()` call for much clearer code.
[Testing: Print full compiler diagnostics.](https://github.com/yandex/yatagan/commit/e06dad1e667eed1ae54fa4f5d69bf2aa418d19d7) 
This improves test code debugging experience.
---------------------------------
No golden diff, no tests changed => No actual behavior is changed.
=> Fix slots codegen, improve test diagnostics.

api/public/api/public.api, api/public/src/main/kotlin/com/yandex/yatagan/Conditional.kt, api/public/src/main/kotlin/com/yandex/yatagan/Conditionals.kt, api/public/src/main/kotlin/com/yandex/yatagan/Provides.kt, core/model/impl/src/main/kotlin/com/yandex/yatagan/core/model/impl/bindingModelsImpl.kt, lang/api/src/main/kotlin/com/yandex/yatagan/lang/BuiltinAnnotation.kt, lang/compiled/src/main/kotlin/com/yandex/yatagan/lang/compiled/CtMethodBase.kt, lang/compiled/src/main/kotlin/com/yandex/yatagan/lang/compiled/CtTypeNameModel.kt, lang/compiled/src/main/kotlin/com/yandex/yatagan/lang/compiled/builtinAnnotationImpls.kt, lang/rt/src/main/kotlin/com/yandex/yatagan/lang/rt/RtMethodImpl.kt, lang/rt/src/main/kotlin/com/yandex/yatagan/lang/rt/builtinAnnotationImpls.kt, testing/tests/build.gradle.kts, testing/tests/src/main/kotlin/com/yandex/yatagan/testing/tests/CompileTestDriverBase.kt, testing/tests/src/main/kotlin/com/yandex/yatagan/testing/tests/DynamicCompileTestDriver.kt, testing/tests/src/main/kotlin/com/yandex/yatagan/testing/tests/JapCompileTestDriver.kt, testing/tests/src/test/kotlin/com/yandex/yatagan/testing/tests/ConditionsTest.kt, testing/tests/src/test/kotlin/com/yandex/yatagan/testing/tests/CoreBindingsFailureTest.kt, testing/tests/src/test/kotlin/com/yandex/yatagan/testing/tests/LoaderCompatibilityTest.kt
[Api: Move Provides.conditionals API.](https://github.com/yandex/yatagan/commit/2e406c97db8313f0c634ea5bdce2f7a6c0989d5e) 
Instead of
`@Provides(Conditional(..), Conditional(..))`
it's now required to write `@Provides @conditional(..) @conditional(..)`.
That is done to fix IDE's issues with `OptIn`s,
where it could require the user to opt-in to
conditions usage, where none were used.
This also improves consistency with other parts
of the API where `Conditional` is a top-level annotation.
Edits in tests are necessary to separate the api
classpath, as this CL introduces a breaking change.
=> Api: Move `Provides.conditionals` API.

core/model/impl/src/main/kotlin/com/yandex/yatagan/core/model/impl/ConditionModelImpl.kt
This CL fully separates parsing from validation,
as per the initial design:
```
Any `MayBeInvalid` model works on the best effort basis,
performing no additional checks at construction/usage time.
Thus, if the model is in fact invalid, the behavior is undefined.
All thorough checks are performed only at validation
```
This CL changes no behavior on the good path.
In case of condition parsing/resolution errors, some errors/warnings could be hidden by others before this CL. Now all of them should be reported correctly.
=> Refactor, Enhance: Condition parsing/resolving.

testing/tests/src/main/kotlin/com/yandex/yatagan/testing/tests/CompileTestDriverBase.kt, testing/tests/src/main/kotlin/com/yandex/yatagan/testing/tests/JapCompileTestDriver.kt, testing/tests/src/test/kotlin/com/yandex/yatagan/testing/tests/LoaderCompatibilityTest.kt
Before the fix it used the runtime api from the version under test,
completely against the test's purpose and rendering it useless.
The fix forces the runtime classpath to be the *current* api classpath,
so the test serves its purpose.
Luckily the test itself was not red after being fixed.
=> [test] Fix LoaderCompatibilityTest

lang/ksp/src/main/kotlin/com/yandex/yatagan/lang/ksp/TypeMap.kt, lang/ksp/src/main/kotlin/com/yandex/yatagan/lang/ksp/nameModels.kt, testing/tests/src/test/kotlin/com/yandex/yatagan/testing/tests/UnresolvedTypeTest.kt, testing/tests/src/test/resources/golden/UnresolvedTypeTest/unresolved-types-KSP-.golden.txt, testing/tests/src/test/resources/golden/UnresolvedTypeTest/unresolved-types-KSP2-.golden.txt
KSP1 still has no support for error types in type arguments -
the whole type is an error then.
Based on resolution of https://github.com/google/ksp/issues/1232
=> Support KSP error types.

api/public/src/main/resources/META-INF/proguard/yatagan.pro
Also include legacy `create` method.
Follow-up to #193
=> [minify] Keep legacy components.
